#
# NB: to run in debug mode, export DEBUG=True
#

dryRun: True # Set to True to just print the pod/node to be deleted, without taking action
gracePeriod: 60 # Seconds that the k8s api call will allow for the pod/node to shut down gracefully. defaults to 0 
updateFrequency: 30 # How frequently it deletes pods/nodes
randomiseFrequency: True # If set to True, it will randomly sleep for a time between 1->updateFrequency seconds, rather than a regular cadence
numPodsToDelete: 2 # How many pods to delete per cycle. Set to 0 to skip, defaults to 1
includedNamespaces: # [optional] Only terminates pods within this namespace. Defaults to all namespaces
  - alchemyst
  - wug
excludedNamespaces: # [optional] Ignores pods in these namespaces. Defaults to kube-system
  - kube-system
  - default
numNodesToDelete: 0 # How many nodes to delete per cycle. Set to 0 to skip [default]
