# NB: to run in debug mode, export DEBUG=True

# Set to True to just print the pod/node to be deleted, without taking action
dryRun: True
# Seconds that the k8s api call will allow for the pod/node to shut down gracefully. defaults to 0
gracePeriod: 60
# How frequently it deletes pods/nodes
updateFrequency: 30
# If set to True, it will randomly sleep for a time between 1->updateFrequency seconds, rather than a regular cadence
randomiseFrequency: True
# How many pods to delete per cycle. Set to 0 to skip, defaults to 1
numPodsToDelete: 2
# [optional] Only terminates pods within this namespace. Defaults to all namespaces
# includedNamespaces: []
# [optional] Ignores pods in these namespaces. Defaults to kube-system
excludedNamespaces: ['kube-system', 'default']
# How many nodes to delete per cycle. Set to 0 to skip [default]
numNodesToDelete: 0
